name: Build Runtime

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yml"
      - "hooks/*"
      - "scripts/*"
      - "dockerfile"
      - "hfmodels.json"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['25.04']
        variant: ['', '-cpu', '-vllm']
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build devel
        uses: docker/build-push-action@v5
        with:
          push: true
          file: dockerfile
          platforms: linux/amd64
          tags: ${{vars.DOCKERHUB_USERNAME}}/tritonserver:${{matrix.version}}${{matrix.variant}}
          build-args: |
            BASE_IMG=hieupth/tritonserverbuild:${{matrix.version}}${{matrix.variant}}
            ENABLE_HOOKS=true
            ENABLE_PIP_INSTALL=true