name: Update Description

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Buil Runtime"]
    types:
      - completed
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/description.yml"
      - README.md

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Update docker description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        repository: ${{vars.DOCKERHUB_USERNAME}}/tritonserver